# Generated by Django 3.0.4 on 2020-03-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('unspecified', 'Unspecified'), ('other', 'Other / I rather not say')], max_length=200, null=True),
        ),
    ]
